### ISSUE TITLE
Example doesn't match output

### ISSUE THREAD

**Issue by coezbek** [raggi/exception_string#1]
The current implementation seems not to match the example on the front-page. When I print a error I get:

```ruby
["boomtest.rb:18:in `go'"]: boom (RuntimeError)
  from boomtest.rb:34:in `foo'
  from boomtest.rb:36
```

Which seems to be due to the `backtrace[0,1]` which returns an array of length 1.

**Comment by raggi** [comment]
This doesn't surprise me too much, as the gem was used with async runtimes on MRI 1.8, which is long since deprecated.

What platforms do you want to use this with?

**Comment by coezbek** [comment]
I am using it with vanilla (YARV) Ruby on Linux.

**Comment by raggi** [comment]
What version?

**Comment by coezbek** [comment]
Switching between 2.7 and 3.1, but does it matter for this question?
